/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package principal;

/**
 *
 * @author SORANY
 */
public class mdiPrincipal extends javax.swing.JFrame {
    private jpFormularioCirculo objFormularioCirculo = new jpFormularioCirculo();
    private jpFormularioCuadrado objFormularioCuadrado = new jpFormularioCuadrado();
    private jpFormularioRectangulo objFormularioRectangulo = new jpFormularioRectangulo();
    private jpFormularioTrianguloR objFormularioTrianguloR = new jpFormularioTrianguloR();
    private jpFormularioRombo objFormularioRombo = new jpFormularioRombo();
    private jpFormularioTrapecio objFormularioTrapecio = new jpFormularioTrapecio();
    
    private void inicializarFormularios(){
        jifFormularioCirculo.setContentPane(objFormularioCirculo);
        objFormularioCirculo.setSize(300,300);
        jifFormularioCirculo.setSize(300,330);
        
        jifFormularioCuadrado.setContentPane(objFormularioCuadrado);
        objFormularioCuadrado.setSize(300,300);
        jifFormularioCuadrado.setSize(300,330);
        
        jifFormularioRectangulo.setContentPane(objFormularioRectangulo);
        objFormularioRectangulo.setSize(300,300);
        jifFormularioRectangulo.setSize(300,330);
        
        jifFormularioTrianguloR.setContentPane(objFormularioTrianguloR);
        objFormularioTrianguloR.setSize(300,300);
        jifFormularioTrianguloR.setSize(300,330);
        
        jifFormularioRombo.setContentPane(objFormularioRombo);
        objFormularioRombo.setSize(300,300);
        jifFormularioRombo.setSize(300,330);
        
        jifFormularioTrapecio.setContentPane(objFormularioTrapecio);
        objFormularioTrapecio.setSize(300,300);
        jifFormularioTrapecio.setSize(300,330);
    }
    /**
     * Creates new form mdiPrincipal
     */
    public mdiPrincipal() {
        initComponents();
        this.inicializarFormularios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jifFormularioCirculo = new javax.swing.JInternalFrame();
        jifFormularioCuadrado = new javax.swing.JInternalFrame();
        jifFormularioRectangulo = new javax.swing.JInternalFrame();
        jifFormularioTrianguloR = new javax.swing.JInternalFrame();
        jifFormularioRombo = new javax.swing.JInternalFrame();
        jifFormularioTrapecio = new javax.swing.JInternalFrame();
        menuBar = new javax.swing.JMenuBar();
        jmArchivo = new javax.swing.JMenu();
        jmiFormularioCirculo = new javax.swing.JMenuItem();
        jmiFormularioCuadrado = new javax.swing.JMenuItem();
        jmiFormularioRectangulo = new javax.swing.JMenuItem();
        jmiFormularioTrianguloR = new javax.swing.JMenuItem();
        jmiFormularioRombo = new javax.swing.JMenuItem();
        jmiFormularioTrapecio = new javax.swing.JMenuItem();
        jmiSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jifFormularioCirculo.setClosable(true);
        jifFormularioCirculo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioCirculo.setVisible(false);

        javax.swing.GroupLayout jifFormularioCirculoLayout = new javax.swing.GroupLayout(jifFormularioCirculo.getContentPane());
        jifFormularioCirculo.getContentPane().setLayout(jifFormularioCirculoLayout);
        jifFormularioCirculoLayout.setHorizontalGroup(
            jifFormularioCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioCirculoLayout.setVerticalGroup(
            jifFormularioCirculoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioCirculo);
        jifFormularioCirculo.setBounds(10, 10, 360, 350);

        jifFormularioCuadrado.setClosable(true);
        jifFormularioCuadrado.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioCuadrado.setVisible(false);

        javax.swing.GroupLayout jifFormularioCuadradoLayout = new javax.swing.GroupLayout(jifFormularioCuadrado.getContentPane());
        jifFormularioCuadrado.getContentPane().setLayout(jifFormularioCuadradoLayout);
        jifFormularioCuadradoLayout.setHorizontalGroup(
            jifFormularioCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioCuadradoLayout.setVerticalGroup(
            jifFormularioCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioCuadrado);
        jifFormularioCuadrado.setBounds(370, 10, 360, 350);

        jifFormularioRectangulo.setClosable(true);
        jifFormularioRectangulo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioRectangulo.setVisible(false);

        javax.swing.GroupLayout jifFormularioRectanguloLayout = new javax.swing.GroupLayout(jifFormularioRectangulo.getContentPane());
        jifFormularioRectangulo.getContentPane().setLayout(jifFormularioRectanguloLayout);
        jifFormularioRectanguloLayout.setHorizontalGroup(
            jifFormularioRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 358, Short.MAX_VALUE)
        );
        jifFormularioRectanguloLayout.setVerticalGroup(
            jifFormularioRectanguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioRectangulo);
        jifFormularioRectangulo.setBounds(730, 10, 370, 350);

        jifFormularioTrianguloR.setClosable(true);
        jifFormularioTrianguloR.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioTrianguloR.setVisible(false);

        javax.swing.GroupLayout jifFormularioTrianguloRLayout = new javax.swing.GroupLayout(jifFormularioTrianguloR.getContentPane());
        jifFormularioTrianguloR.getContentPane().setLayout(jifFormularioTrianguloRLayout);
        jifFormularioTrianguloRLayout.setHorizontalGroup(
            jifFormularioTrianguloRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioTrianguloRLayout.setVerticalGroup(
            jifFormularioTrianguloRLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioTrianguloR);
        jifFormularioTrianguloR.setBounds(10, 380, 360, 540);

        jifFormularioRombo.setClosable(true);
        jifFormularioRombo.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioRombo.setVisible(false);

        javax.swing.GroupLayout jifFormularioRomboLayout = new javax.swing.GroupLayout(jifFormularioRombo.getContentPane());
        jifFormularioRombo.getContentPane().setLayout(jifFormularioRomboLayout);
        jifFormularioRomboLayout.setHorizontalGroup(
            jifFormularioRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioRomboLayout.setVerticalGroup(
            jifFormularioRomboLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioRombo);
        jifFormularioRombo.setBounds(370, 380, 360, 350);

        jifFormularioTrapecio.setClosable(true);
        jifFormularioTrapecio.setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        jifFormularioTrapecio.setVisible(false);

        javax.swing.GroupLayout jifFormularioTrapecioLayout = new javax.swing.GroupLayout(jifFormularioTrapecio.getContentPane());
        jifFormularioTrapecio.getContentPane().setLayout(jifFormularioTrapecioLayout);
        jifFormularioTrapecioLayout.setHorizontalGroup(
            jifFormularioTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jifFormularioTrapecioLayout.setVerticalGroup(
            jifFormularioTrapecioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        desktopPane.add(jifFormularioTrapecio);
        jifFormularioTrapecio.setBounds(730, 380, 370, 350);

        jmArchivo.setMnemonic('f');
        jmArchivo.setText("Archivo");

        jmiFormularioCirculo.setMnemonic('o');
        jmiFormularioCirculo.setText("Formulario Circulo");
        jmiFormularioCirculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioCirculoActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiFormularioCirculo);

        jmiFormularioCuadrado.setMnemonic('s');
        jmiFormularioCuadrado.setText("Formulario Cuadrado");
        jmiFormularioCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioCuadradoActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiFormularioCuadrado);

        jmiFormularioRectangulo.setText("Formulario Rectángulo");
        jmiFormularioRectangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioRectanguloActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiFormularioRectangulo);

        jmiFormularioTrianguloR.setText("Formulario TrianguloRectángulo");
        jmiFormularioTrianguloR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioTrianguloRActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiFormularioTrianguloR);

        jmiFormularioRombo.setText("Formulario Rombo");
        jmiFormularioRombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioRomboActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiFormularioRombo);

        jmiFormularioTrapecio.setText("Formulario Trapecio");
        jmiFormularioTrapecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiFormularioTrapecioActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiFormularioTrapecio);

        jmiSalir.setMnemonic('x');
        jmiSalir.setText("Salir");
        jmiSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiSalirActionPerformed(evt);
            }
        });
        jmArchivo.add(jmiSalir);

        menuBar.add(jmArchivo);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1121, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 830, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jmiSalirActionPerformed

    private void jmiFormularioCirculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioCirculoActionPerformed
        jifFormularioCirculo.setVisible(true);
    }//GEN-LAST:event_jmiFormularioCirculoActionPerformed

    private void jmiFormularioCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioCuadradoActionPerformed
        jifFormularioCuadrado.setVisible(true);
    }//GEN-LAST:event_jmiFormularioCuadradoActionPerformed

    private void jmiFormularioRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioRectanguloActionPerformed
        jifFormularioRectangulo.setVisible(true);
    }//GEN-LAST:event_jmiFormularioRectanguloActionPerformed

    private void jmiFormularioTrianguloRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioTrianguloRActionPerformed
        jifFormularioTrianguloR.setVisible(true);
    }//GEN-LAST:event_jmiFormularioTrianguloRActionPerformed

    private void jmiFormularioRomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioRomboActionPerformed
        jifFormularioRombo.setVisible(true);
    }//GEN-LAST:event_jmiFormularioRomboActionPerformed

    private void jmiFormularioTrapecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiFormularioTrapecioActionPerformed
        jifFormularioTrapecio.setVisible(true);
    }//GEN-LAST:event_jmiFormularioTrapecioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mdiPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mdiPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JInternalFrame jifFormularioCirculo;
    private javax.swing.JInternalFrame jifFormularioCuadrado;
    private javax.swing.JInternalFrame jifFormularioRectangulo;
    private javax.swing.JInternalFrame jifFormularioRombo;
    private javax.swing.JInternalFrame jifFormularioTrapecio;
    private javax.swing.JInternalFrame jifFormularioTrianguloR;
    private javax.swing.JMenu jmArchivo;
    private javax.swing.JMenuItem jmiFormularioCirculo;
    private javax.swing.JMenuItem jmiFormularioCuadrado;
    private javax.swing.JMenuItem jmiFormularioRectangulo;
    private javax.swing.JMenuItem jmiFormularioRombo;
    private javax.swing.JMenuItem jmiFormularioTrapecio;
    private javax.swing.JMenuItem jmiFormularioTrianguloR;
    private javax.swing.JMenuItem jmiSalir;
    private javax.swing.JMenuBar menuBar;
    // End of variables declaration//GEN-END:variables

}
